version: "3.1"
services:

    #Application
    php-fpm:
      image: blog-hexagonal/php
      build: docker/php-fpm
      container_name: app
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/local.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    #WebServer
    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"